name: lighthouse-ci demo

on:
  push:
    branches:
      - master

jobs:
  lhci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: npm install, build
        run: |
          yarn
          npm run build
      - name: run lighthouse-ci
        run: |
          npm install && npm install -g @lhci/cli@0.13.x
          lhci autorun --collect.staticDistDir=./dist --
          upload.target=temporary-public-storage || echo "LHCI failed!"
        env:
          LHCI_GITHUB_APP_TOKEN: ${{secrets.LH_CI_GITHUB_APP_TOKEN}}
